// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDslXsjTqw-VLtUJG4AAyNWIlCxoh4E5Js',
    appId: '1:44525309522:web:363ebc954f95503869198b',
    messagingSenderId: '44525309522',
    projectId: 'reaminder-app',
    authDomain: 'reaminder-app.firebaseapp.com',
    storageBucket: 'reaminder-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIdq0Hix65EQVRlf6W1dvhvZ0ppP-922Q',
    appId: '1:44525309522:android:42bed06bbe649e9169198b',
    messagingSenderId: '44525309522',
    projectId: 'reaminder-app',
    storageBucket: 'reaminder-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuZLVrMmUNV1Rh57o5makNhGZwmGQ0lY0',
    appId: '1:44525309522:ios:0137eca980e18df869198b',
    messagingSenderId: '44525309522',
    projectId: 'reaminder-app',
    storageBucket: 'reaminder-app.firebasestorage.app',
    iosBundleId: 'com.example.snoozeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuZLVrMmUNV1Rh57o5makNhGZwmGQ0lY0',
    appId: '1:44525309522:ios:0137eca980e18df869198b',
    messagingSenderId: '44525309522',
    projectId: 'reaminder-app',
    storageBucket: 'reaminder-app.firebasestorage.app',
    iosBundleId: 'com.example.snoozeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDslXsjTqw-VLtUJG4AAyNWIlCxoh4E5Js',
    appId: '1:44525309522:web:5a8e88b0243afc2469198b',
    messagingSenderId: '44525309522',
    projectId: 'reaminder-app',
    authDomain: 'reaminder-app.firebaseapp.com',
    storageBucket: 'reaminder-app.firebasestorage.app',
  );
}
